# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chunk.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hunk.proto\"\x17\n\x05\x43hunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x17\n\x05Reply\x12\x0e\n\x06length\x18\x01 \x01(\x05\"$\n\x0fTransferRequest\x12\x11\n\tfile_size\x18\x01 \x01(\x05\"(\n\x10TransferResponse\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x32\x83\x01\n\nFileServer\x12\x1c\n\x06upload\x12\x06.Chunk\x1a\x06.Reply\"\x00(\x01\x12 \n\x08\x64ownload\x12\x08.Request\x1a\x06.Chunk\"\x00\x30\x01\x12\x35\n\x0cTransferFile\x12\x10.TransferRequest\x1a\x11.TransferResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chunk_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHUNK']._serialized_start=15
  _globals['_CHUNK']._serialized_end=38
  _globals['_REQUEST']._serialized_start=40
  _globals['_REQUEST']._serialized_end=63
  _globals['_REPLY']._serialized_start=65
  _globals['_REPLY']._serialized_end=88
  _globals['_TRANSFERREQUEST']._serialized_start=90
  _globals['_TRANSFERREQUEST']._serialized_end=126
  _globals['_TRANSFERRESPONSE']._serialized_start=128
  _globals['_TRANSFERRESPONSE']._serialized_end=168
  _globals['_FILESERVER']._serialized_start=171
  _globals['_FILESERVER']._serialized_end=302
# @@protoc_insertion_point(module_scope)
